[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = "1.43.0"
tokio-tungstenite = "0.26.1"
uuid = { version = "1.11.0", features = ["v4", "serde"] }
serde_json = "1.0.135"